version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: nodeapp
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:123456@mongo:27017/test?authSource=admin

volumes:
  mongo-data: