FROM node:20-slim

RUN apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update -y \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm config set fetch-retry-mintimeout 20000 \
    && npm config set fetch-retry-maxtimeout 120000 \
    && npm config set fetch-retries 5 \
    && npm install

COPY prisma ./prisma
RUN npx prisma generate
COPY . .
EXPOSE 3050
CMD ["npm", "start"]
