services:
  recruitment-db:
    image: postgres:16-alpine
    container_name: recruitment_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: recruitment_db
    ports:
      - "5433:5432"
    volumes:
      - recruitment_pgdata:/var/lib/postgresql/data
    networks:
      - recruitment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  recruitment-service:
    build: .
    container_name: recruitment_service
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      recruitment-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://recruitment-db:5432/recruitment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: your_super_secret_key
      SERVICES_USER_SERVICE_URL: http://host.docker.internal:3001
      SERVICES_SURVEY_SERVICE_URL: http://host.docker.internal:4000
    networks:
      - recruitment-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  recruitment-network:
    driver: bridge

volumes:
  recruitment_pgdata: